// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddPuppy struct {
	PuppyID   string   `json:"puppyId"`
	ParentsID []string `json:"parentsId"`
}

type Breed struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Dog struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Age     *int     `json:"age"`
	Breed   *Breed   `json:"breed"`
	Puppies []*Puppy `json:"puppies"`
}

type NewBreed struct {
	Name string `json:"name"`
}

type NewDog struct {
	Name      string   `json:"name"`
	Age       *int     `json:"age"`
	BreedID   string   `json:"breedId"`
	PuppiesID []string `json:"puppiesId"`
}

type NewPuppy struct {
	Name      string   `json:"name"`
	Color     *string  `json:"color"`
	BreedID   string   `json:"breedId"`
	ParentsID []string `json:"parentsId"`
}

type Puppy struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Color   *string `json:"color"`
	Breed   *Breed  `json:"breed"`
	Parents []*Dog  `json:"parents"`
}
